### PR TITLE
.NET 8, dependency updates, and dependabot

### PR DESCRIPTION
**Pull request by david-brink-talogy**

### CODE REVIEW

**Comment by sklose** [comment]
where is the icon from? it looks nice, but let's make sure we are not violating any copyrights.

**Comment by david-brink-talogy** [comment]
I thr

> where is the icon from? it looks nice, but let's make sure we are not violating any copyrights.

I threw a number of prompts through Google's AI and then tweaked it a bit.  My understanding is the major AIs give copyright to the creator.

**Review by Bykiev — APPROVED** [review]

**Comment by sklose** [comment]
> I threw a number of prompts through Google's ImageFX AI and then tweaked it a bit. My understanding is the major AIs give copyright to the creator.

sounds good, nice job on the icon 🎉

**Review by sklose — APPROVED** [review]

**Comment by Bykiev** [comment]
Should be [appveyor.yml](https://github.com/sklose/NCalc2/blob/master/appveyor.yml) update too?

**Comment by david-brink-talogy** [comment]
> Should be [appveyor.yml](https://github.com/sklose/NCalc2/blob/master/appveyor.yml) updated too?

Thanks for catching this.  I made this change while you and I were chatting yesterday about how to change the minor version.  I didn't intend to commit it.  It has been reverted.

**Pull request merged**
